<a href="https://colab.research.google.com/github/samuelyota/TugasDataMining/blob/main/Processing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv('data.csv')
X=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [3]:
print(X)

[['Beras' 44.0 72000.0]
 ['Minyak' 27.0 48000.0]
 ['Gula' 30.0 54000.0]
 ['IkanLele' 38.0 61000.0]
 ['Telor' 40.0 nan]
 ['Bawang Merah' 35.0 58000.0]
 ['Tepung' nan 52000.0]
 ['DagingKambing' 48.0 79000.0]
 ['DagingSapi' 50.0 83000.0]
 ['IkanBandeng' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [6]:
print(X)

[['Beras' 44.0 72000.0]
 ['Minyak' 27.0 48000.0]
 ['Gula' 30.0 54000.0]
 ['IkanLele' 38.0 61000.0]
 ['Telor' 40.0 63777.77777777778]
 ['Bawang Merah' 35.0 58000.0]
 ['Tepung' 38.77777777777778 52000.0]
 ['DagingKambing' 48.0 79000.0]
 ['DagingSapi' 50.0 83000.0]
 ['IkanBandeng' 37.0 67000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X).toarray()

In [9]:
print(X)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 2.70000000e+01 4.80000000e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.80000000e+01 6.10000000e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split( X, y, test_size=0.2, random_state=1 )

In [13]:
print(X_train)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.80000000e+01 6.10000000e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 2.70000000e+01 4.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0

In [14]:
print(X_test)

[[0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00
  0.0e+00 3.0e+01 5.4e+04]
 [0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e+00 0.0e+00 0.0e+00 0.0e+00
  0.0e+00 3.7e+01 6.7e+04]]


In [15]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [16]:
print(y_test)

[0 1]


In [17]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train [:, 3:]= sc.fit_transform(X_train[:, 3:])
X_test [:, 3:] = sc.transform(X_test[:, 3:])

In [19]:
print(X_train)

[[ 0.          0.          0.         -0.37796447  0.          0.
  -0.37796447 -0.37796447 -0.37796447  2.64575131 -0.19159184 -1.07812594]
 [ 0.          0.          0.         -0.37796447  0.          0.
  -0.37796447 -0.37796447  2.64575131 -0.37796447 -0.01411729 -0.07013168]
 [ 0.          1.          0.         -0.37796447  0.          0.
  -0.37796447 -0.37796447 -0.37796447 -0.37796447  0.56670851  0.63356243]
 [ 0.          0.          0.         -0.37796447  0.          0.
   2.64575131 -0.37796447 -0.37796447 -0.37796447 -0.30453019 -0.30786617]
 [ 0.          0.          0.         -0.37796447  0.          0.
  -0.37796447  2.64575131 -0.37796447 -0.37796447 -1.90180114 -1.42046362]
 [ 0.          0.          1.         -0.37796447  0.          0.
  -0.37796447 -0.37796447 -0.37796447 -0.37796447  1.14753431  1.23265336]
 [ 0.          0.          0.          2.64575131  0.          0.
  -0.37796447 -0.37796447 -0.37796447 -0.37796447  1.43794721  1.57499104]
 [ 1.        

In [20]:
print(X_test)

[[ 0.          0.          0.         -0.37796447  1.          0.
  -0.37796447 -0.37796447 -0.37796447 -0.37796447 -1.46618179 -0.9069571 ]
 [ 0.          0.          0.         -0.37796447  0.          1.
  -0.37796447 -0.37796447 -0.37796447 -0.37796447 -0.44973664  0.20564034]]
